# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_auto_20160509_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='category',
        ),
        migrations.AddField(
            model_name='entry',
            name='category',
            field=models.ManyToManyField(to='magazine.Category'),
        ),
    ]
