# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_auto_20160509_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='well_image',
            field=models.CharField(blank=True, help_text=b"Image to fill this entry's well (higher priority than 'well text').", max_length=200),
        ),
        migrations.AddField(
            model_name='entry',
            name='well_text',
            field=models.TextField(blank=True, help_text=b"Text to fill this entry's well (if blank, 'entry content' will be used)."),
        ),
    ]
