# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-04 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0007_auto_20160710_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.OneToOneField(help_text='This category will appear in the header-menu', on_delete=django.db.models.deletion.CASCADE, to='magazine.Category')),
            ],
        ),
    ]
