# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-09 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0008_maincategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='introduction',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='category',
            field=models.OneToOneField(help_text='This category will appear in the header-menu. If there are no main-categories then the most popular ones will be displayed.', on_delete=django.db.models.deletion.CASCADE, to='magazine.Category'),
        ),
    ]
