# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-09 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0009_auto_20170909_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='well_image',
            field=models.CharField(blank=True, help_text="Image to fill this issue's well (higher priority than 'well text').", max_length=200),
        ),
        migrations.AddField(
            model_name='issue',
            name='well_text',
            field=models.TextField(blank=True, help_text="Text to fill this issue's well (if blank, 'issue content' will be used)."),
        ),
    ]
