# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-09 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0010_auto_20170909_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
