# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-18 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0011_issue_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='issue',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazine.Issue'),
        ),
    ]
